const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Tilemap,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Plugins.Text,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Pin,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Timeline,
		C3.Plugins.AJAX,
		C3.Plugins.Massive_Cube_Rex_CSV2Array,
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.len,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Behaviors.lunarray_LiteTween.Acts.SetTarget,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.TextBox.Acts.SetPlaceholder,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Button.Acts.SetText,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Timeline.Cnds.OnTimelineFinishedByTags,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Massive_Cube_Rex_CSV2Array.Acts.CSV2Array,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Text.Acts.AppendText
	];
};
self.C3_JsPropNameTable = [
	{bg_home: 0},
	{btn_materi: 0},
	{btn_play: 0},
	{tulisanJAWARA: 0},
	{DialogText: 0},
	{WaitTime: 0},
	{Solid: 0},
	{ClueTrigger: 0},
	{corps: 0},
	{fish: 0},
	{home: 0},
	{landStreet: 0},
	{NPC_Clue1: 0},
	{objectStreet: 0},
	{CurrentMove: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{Player3: 0},
	{spr_deco_coracle_land: 0},
	{Sprite10: 0},
	{tree1: 0},
	{tree2: 0},
	{btn_pause3: 0},
	{FinishTest: 0},
	{NPC2: 0},
	{NPC_Clue2: 0},
	{NPC_Clue3: 0},
	{box_dialogAwal: 0},
	{box_dialogClue: 0},
	{bg_charLawan: 0},
	{Build1: 0},
	{build2: 0},
	{build4: 0},
	{Build_3: 0},
	{Char_lawan1: 0},
	{Char_lawan2: 0},
	{Char_lawan3: 0},
	{Char_lawan4: 0},
	{DUSUNRAJIN: 0},
	{DUSUNRENDAHHATI: 0},
	{DUSUNSANGJUJUR: 0},
	{DUSUNSiHemat: 0},
	{Ellipse: 0},
	{mapLevel1: 0},
	{mapLevel2: 0},
	{mapLevel3: 0},
	{mapLevel4: 0},
	{joystick: 0},
	{npc_dialogClue1: 0},
	{npc_dialogClue2: 0},
	{npc_dialogClue3: 0},
	{shadow: 0},
	{text_dialogAwal: 0},
	{text_dialogClue: 0},
	{board_clue1: 0},
	{board_clue2: 0},
	{board_clue3: 0},
	{DialogPerkenalan: 0},
	{GUI_Enter: 0},
	{ClueText2: 0},
	{M_box: 0},
	{btn_tidak2: 0},
	{btn_ya2: 0},
	{Askmove: 0},
	{AksaraLegena2: 0},
	{aksaraSwara: 0},
	{aksaraWanda: 0},
	{bg_materiSwara: 0},
	{btn_backLegena: 0},
	{btn_backMateri: 0},
	{btn_backSwara: 0},
	{btn_kiriLegena: 0},
	{Hanacaraka: 0},
	{LiteTween: 0},
	{swara_wulu: 0},
	{wanda_wignyan: 0},
	{Materi: 0},
	{materiAksaraSwara: 0},
	{materiAksaraWanda: 0},
	{pilihanMateri: 0},
	{swara_suku: 0},
	{swara_taling: 0},
	{swara_tarung: 0},
	{swara_pepet: 0},
	{wanda_layar: 0},
	{wanda_cecak: 0},
	{wanda_pangkon: 0},
	{bg_materiWanda: 0},
	{bg_materiLegena: 0},
	{bg_petunjuk: 0},
	{id: 0},
	{setX: 0},
	{setY: 0},
	{btn_opsiInfo: 0},
	{btn_opsiInfo2: 0},
	{btn_opsiInfo3: 0},
	{btn_opsiInfo4: 0},
	{clue_textInfo: 0},
	{jawara_textInfo: 0},
	{petunjuk: 0},
	{bg_tingkatan: 0},
	{btn_back: 0},
	{value: 0},
	{level_1: 0},
	{complete_before: 0},
	{level_2: 0},
	{compare_before3: 0},
	{level_3: 0},
	{compare_before4: 0},
	{level_4: 0},
	{Text5: 0},
	{box_Answer: 0},
	{Pin: 0},
	{box_complete: 0},
	{boxDarah: 0},
	{boxSoal: 0},
	{boxWaktuSkor: 0},
	{COMPLETELEVEL: 0},
	{effectAttackLawan: 0},
	{effectAttackPemain: 0},
	{Group: 0},
	{skorTertinggi: 0},
	{Text_jawaban: 0},
	{Text_jumlahSoal: 0},
	{text_levelcomplete: 0},
	{Text_skor: 0},
	{Text_soal: 0},
	{Text_soal2: 0},
	{Text_soal3: 0},
	{Text_soal4: 0},
	{Text_waktu: 0},
	{TextSoal: 0},
	{TextSoalPetik: 0},
	{TiledBackgroundLawan: 0},
	{TiledBackgroundPemain: 0},
	{TiledBackgroundLawan2: 0},
	{TiledBackgroundLawan3: 0},
	{TiledBackgroundLawan4: 0},
	{box_pengaturan: 0},
	{btn_music_off: 0},
	{btn_music_on: 0},
	{Text_suara: 0},
	{btn_close: 0},
	{btn_homeReplay: 0},
	{btn_info: 0},
	{btn_setting: 0},
	{btn_tdkNew: 0},
	{btn_yaNew: 0},
	{btnResumeExit: 0},
	{button_close: 0},
	{pause: 0},
	{TextPause: 0},
	{inv1: 0},
	{inv2: 0},
	{inv3: 0},
	{inv_clue: 0},
	{Inventory: 0},
	{Slot_ID: 0},
	{Item_Name: 0},
	{Item_Quantity: 0},
	{Sort_Prio: 0},
	{obj_inv_slot: 0},
	{hitam2: 0},
	{hitam3: 0},
	{hitam4: 0},
	{layerHitam: 0},
	{layerHitamFirst: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Data_Acak: 0},
	{Data_Huruf: 0},
	{LocalStorage: 0},
	{game_background_: 0},
	{Mouse: 0},
	{Audio: 0},
	{Combo: 0},
	{Text: 0},
	{LogoSplash: 0},
	{TimelineController: 0},
	{Lab: 0},
	{box_inputName: 0},
	{btnSubmit: 0},
	{AJAX: 0},
	{CSVToArray: 0},
	{Array: 0},
	{Sprite: 0},
	{textLead: 0},
	{lb1_name: 0},
	{send: 0},
	{ssssssss: 0},
	{Name: 0},
	{btn_leaderboard: 0},
	{lb1_score: 0},
	{lb1_time: 0},
	{music: 0},
	{cek_level: 0},
	{cek_npcClue: 0},
	{user: 0},
	{S: 0},
	{SheetCode: 0},
	{Max_combo: 0},
	{Base_score: 0},
	{Wrong: 0},
	{List_salah: 0},
	{Correct: 0},
	{LoadProgress: 0},
	{IsUploading: 0},
	{Time_temp: 0},
	{List_soal: 0},
	{Resp_time: 0},
	{WebAppURL: 0},
	{Darah: 0},
	{DarahLawan: 0},
	{Waktu: 0},
	{GameMulai: 0},
	{JawabanSoal: 0},
	{Pilihan: 0},
	{DataScore: 0},
	{DataSoal: 0},
	{HisHighScore: 0},
	{rand: 0},
	{Waktu3: 0},
	{DataScore3: 0},
	{HisHighScore3: 0},
	{DarahLawan3: 0},
	{Waktu2: 0},
	{DataScore2: 0},
	{HisHighScore2: 0},
	{DarahLawan2: 0},
	{Waktu4: 0},
	{DataScore4: 0},
	{HisHighScore4: 0},
	{DarahLawan4: 0}
];

self.InstanceType = {
	bg_home: class extends self.ISpriteInstance {},
	btn_materi: class extends self.ISpriteInstance {},
	btn_play: class extends self.ISpriteInstance {},
	tulisanJAWARA: class extends self.ISpriteInstance {},
	ClueTrigger: class extends self.ISpriteInstance {},
	corps: class extends self.ITilemapInstance {},
	fish: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	landStreet: class extends self.ITilemapInstance {},
	NPC_Clue1: class extends self.ISpriteInstance {},
	objectStreet: class extends self.ITilemapInstance {},
	Player3: class extends self.ISpriteInstance {},
	spr_deco_coracle_land: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	tree1: class extends self.ISpriteInstance {},
	tree2: class extends self.ISpriteInstance {},
	btn_pause3: class extends self.ISpriteInstance {},
	FinishTest: class extends self.ISpriteInstance {},
	NPC2: class extends self.ISpriteInstance {},
	NPC_Clue2: class extends self.ISpriteInstance {},
	NPC_Clue3: class extends self.ISpriteInstance {},
	box_dialogAwal: class extends self.ISpriteInstance {},
	box_dialogClue: class extends self.ISpriteInstance {},
	bg_charLawan: class extends self.ISpriteInstance {},
	Build1: class extends self.ISpriteInstance {},
	build2: class extends self.ISpriteInstance {},
	build4: class extends self.ISpriteInstance {},
	Build_3: class extends self.ISpriteInstance {},
	Char_lawan1: class extends self.ISpriteInstance {},
	Char_lawan2: class extends self.ISpriteInstance {},
	Char_lawan3: class extends self.ISpriteInstance {},
	Char_lawan4: class extends self.ISpriteInstance {},
	DUSUNRAJIN: class extends self.ISpriteInstance {},
	DUSUNRENDAHHATI: class extends self.ISpriteInstance {},
	DUSUNSANGJUJUR: class extends self.ISpriteInstance {},
	DUSUNSiHemat: class extends self.ISpriteInstance {},
	Ellipse: class extends self.ISpriteInstance {},
	mapLevel1: class extends self.ISpriteInstance {},
	mapLevel2: class extends self.ISpriteInstance {},
	mapLevel3: class extends self.ISpriteInstance {},
	mapLevel4: class extends self.ISpriteInstance {},
	joystick: class extends self.ISpriteInstance {},
	npc_dialogClue1: class extends self.ISpriteInstance {},
	npc_dialogClue2: class extends self.ISpriteInstance {},
	npc_dialogClue3: class extends self.ISpriteInstance {},
	shadow: class extends self.ISpriteInstance {},
	text_dialogAwal: class extends self.ITextInstance {},
	text_dialogClue: class extends self.ITextInstance {},
	board_clue1: class extends self.ISpriteInstance {},
	board_clue2: class extends self.ISpriteInstance {},
	board_clue3: class extends self.ISpriteInstance {},
	DialogPerkenalan: class extends self.ITextInstance {},
	GUI_Enter: class extends self.ITextInstance {},
	M_box: class extends self.ISpriteInstance {},
	btn_tidak2: class extends self.ISpriteInstance {},
	btn_ya2: class extends self.ISpriteInstance {},
	Askmove: class extends self.ITextInstance {},
	AksaraLegena2: class extends self.ISpriteInstance {},
	aksaraSwara: class extends self.ISpriteInstance {},
	aksaraWanda: class extends self.ISpriteInstance {},
	bg_materiSwara: class extends self.ISpriteInstance {},
	btn_backLegena: class extends self.ISpriteInstance {},
	btn_backMateri: class extends self.ISpriteInstance {},
	btn_backSwara: class extends self.ISpriteInstance {},
	btn_kiriLegena: class extends self.ISpriteInstance {},
	Hanacaraka: class extends self.ISpriteInstance {},
	swara_wulu: class extends self.ISpriteInstance {},
	wanda_wignyan: class extends self.ISpriteInstance {},
	Materi: class extends self.ISpriteInstance {},
	materiAksaraSwara: class extends self.ISpriteInstance {},
	materiAksaraWanda: class extends self.ISpriteInstance {},
	pilihanMateri: class extends self.ISpriteInstance {},
	swara_suku: class extends self.ISpriteInstance {},
	swara_taling: class extends self.ISpriteInstance {},
	swara_tarung: class extends self.ISpriteInstance {},
	swara_pepet: class extends self.ISpriteInstance {},
	wanda_layar: class extends self.ISpriteInstance {},
	wanda_cecak: class extends self.ISpriteInstance {},
	wanda_pangkon: class extends self.ISpriteInstance {},
	bg_materiWanda: class extends self.ISpriteInstance {},
	bg_materiLegena: class extends self.ISpriteInstance {},
	bg_petunjuk: class extends self.ISpriteInstance {},
	btn_opsiInfo: class extends self.ISpriteInstance {},
	btn_opsiInfo2: class extends self.ISpriteInstance {},
	btn_opsiInfo3: class extends self.ISpriteInstance {},
	btn_opsiInfo4: class extends self.ISpriteInstance {},
	clue_textInfo: class extends self.ISpriteInstance {},
	jawara_textInfo: class extends self.ISpriteInstance {},
	petunjuk: class extends self.ISpriteInstance {},
	bg_tingkatan: class extends self.ISpriteInstance {},
	btn_back: class extends self.ISpriteInstance {},
	level_1: class extends self.ISpriteInstance {},
	level_2: class extends self.ISpriteInstance {},
	level_3: class extends self.ISpriteInstance {},
	level_4: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	box_Answer: class extends self.ISpriteInstance {},
	box_complete: class extends self.ISpriteInstance {},
	boxDarah: class extends self.ISpriteInstance {},
	boxSoal: class extends self.ISpriteInstance {},
	boxWaktuSkor: class extends self.ISpriteInstance {},
	COMPLETELEVEL: class extends self.ISpriteInstance {},
	effectAttackLawan: class extends self.ISpriteInstance {},
	effectAttackPemain: class extends self.ISpriteInstance {},
	Group: class extends self.ISpriteInstance {},
	skorTertinggi: class extends self.ITextInstance {},
	Text_jawaban: class extends self.ITextInstance {},
	Text_jumlahSoal: class extends self.ITextInstance {},
	text_levelcomplete: class extends self.ITextInstance {},
	Text_skor: class extends self.ITextInstance {},
	Text_soal: class extends self.ISpriteInstance {},
	Text_soal2: class extends self.ISpriteInstance {},
	Text_soal3: class extends self.ISpriteInstance {},
	Text_soal4: class extends self.ISpriteInstance {},
	Text_waktu: class extends self.ITextInstance {},
	TextSoal: class extends self.ITextInstance {},
	TextSoalPetik: class extends self.ITextInstance {},
	TiledBackgroundLawan: class extends self.ITiledBackgroundInstance {},
	TiledBackgroundPemain: class extends self.ITiledBackgroundInstance {},
	TiledBackgroundLawan2: class extends self.ITiledBackgroundInstance {},
	TiledBackgroundLawan3: class extends self.ITiledBackgroundInstance {},
	TiledBackgroundLawan4: class extends self.ITiledBackgroundInstance {},
	box_pengaturan: class extends self.ISpriteInstance {},
	btn_music_off: class extends self.ISpriteInstance {},
	btn_music_on: class extends self.ISpriteInstance {},
	Text_suara: class extends self.ITextInstance {},
	btn_close: class extends self.ISpriteInstance {},
	btn_homeReplay: class extends self.ISpriteInstance {},
	btn_info: class extends self.ISpriteInstance {},
	btn_setting: class extends self.ISpriteInstance {},
	btn_tdkNew: class extends self.ISpriteInstance {},
	btn_yaNew: class extends self.ISpriteInstance {},
	btnResumeExit: class extends self.ISpriteInstance {},
	button_close: class extends self.ISpriteInstance {},
	pause: class extends self.ISpriteInstance {},
	TextPause: class extends self.ITextInstance {},
	inv1: class extends self.ISpriteInstance {},
	inv2: class extends self.ISpriteInstance {},
	inv3: class extends self.ISpriteInstance {},
	inv_clue: class extends self.ISpriteInstance {},
	Inventory: class extends self.ISpriteInstance {},
	obj_inv_slot: class extends self.ISpriteInstance {},
	hitam2: class extends self.ISpriteInstance {},
	hitam3: class extends self.ISpriteInstance {},
	hitam4: class extends self.ISpriteInstance {},
	layerHitam: class extends self.ISpriteInstance {},
	layerHitamFirst: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Data_Acak: class extends self.IArrayInstance {},
	Data_Huruf: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	game_background_: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Combo: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	LogoSplash: class extends self.ISpriteInstance {},
	TimelineController: class extends self.IInstance {},
	Lab: class extends self.ISpriteInstance {},
	box_inputName: class extends self.ISpriteInstance {},
	btnSubmit: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	CSVToArray: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	Sprite: class extends self.ISpriteInstance {},
	textLead: class extends self.ITextInstance {},
	lb1_name: class extends self.ITextInstance {},
	send: class extends self.IButtonInstance {},
	ssssssss: class extends self.ITextInstance {},
	Name: class extends self.ITextInputInstance {},
	btn_leaderboard: class extends self.ISpriteInstance {},
	lb1_score: class extends self.ITextInstance {},
	lb1_time: class extends self.ITextInstance {}
}